### ISSUE TITLE
Mismatched binary path in setup.sh

### ISSUE THREAD

**Issue by lacabra** [figment-networks/hubble#7]
When running `./setup/bootstrap.sh`, which in turn calls `./setup/templates/setup.sh` it throws the following error:
```bash
bash: line 42: /hubble/ruby-2.5.0/gem: No such file or directory
```
L42 should instead read: 
```bash
/hubble/ruby-2.5.0/bin/gem install bundler
```
note the missing **/bin** above

**Comment by rfunduk** [comment]
Thanks @lacabra 💯
